create table if not exists public.friend_articles (
  id bigint generated by default as identity primary key,
  slug text not null,
  title text not null,
  excerpt text,
  content text not null,
  author_name text not null,
  author_profile text,
  author_avatar_url text,
  tags text[] not null default '{}'::text[],
  is_published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint friend_articles_slug_key unique (slug),
  constraint friend_articles_published_requires_time
    check ((not is_published) or (published_at is not null))
);

create index if not exists friend_articles_published_at_idx
  on public.friend_articles (is_published, published_at desc);

create index if not exists friend_articles_author_name_idx
  on public.friend_articles (author_name);

alter table public.friend_articles enable row level security;

drop policy if exists "Allow public read published friend articles" on public.friend_articles;
create policy "Allow public read published friend articles"
on public.friend_articles
for select
to anon
using (is_published = true);
