create table if not exists public.post_likes (
  id bigint generated by default as identity primary key,
  post_slug text not null,
  device_id text not null,
  is_active boolean not null default true,
  first_liked_at timestamptz not null default now(),
  last_liked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint post_likes_post_slug_device_id_key unique (post_slug, device_id)
);

create index if not exists post_likes_post_slug_idx
  on public.post_likes (post_slug);

create index if not exists post_likes_active_idx
  on public.post_likes (post_slug, is_active);

alter table public.post_likes enable row level security;

create policy "Allow public read active likes"
on public.post_likes
for select
to anon
using (true);

create policy "Allow public insert likes"
on public.post_likes
for insert
to anon
with check (true);

create policy "Allow public update own device likes"
on public.post_likes
for update
to anon
using (true)
with check (true);
